"""add_status_and_speed

Revision ID: c5a7bdb9f6e3
Revises: 1b60aa8347fb
Create Date: 2026-06-21 20:34:08.968248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c5a7bdb9f6e3'
down_revision: Union[str, Sequence[str], None] = '1b60aa8347fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_logs', sa.Column('speed', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'status')
    op.drop_column('location_logs', 'speed')
    # ### end Alembic commands ###
